"""Removed password_hash from Employee model

Revision ID: bd98afb835ba
Revises: 6ef7da8bbb02
Create Date: 2025-07-02 11:18:58.536842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd98afb835ba'
down_revision = '6ef7da8bbb02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('employee_pin_code_key'), type_='unique')
        batch_op.create_unique_constraint('uq_employee_pin_code', ['pin_code'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_employee_pin_code', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('employee_pin_code_key'), ['pin_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
